### ISSUE TITLE
Can't reproduce sample

### ISSUE THREAD

**Issue by opavlyuk** [noseka1/vertx-eventbus-wireshark-dissector#1]
Hello, @noseka1 

I followed [instructions](https://github.com/noseka1/vertx-eventbus-wireshark-dissector/blob/master/vertx_eventbus_dissector.lua#L16-L28) with your [sample](https://github.com/noseka1/vertx-eventbus-wireshark-dissector/blob/master/vertx_eventbus_sample_capture.pcapng), but got unexpected result.
Wireshark ver:
```3.2.3 (Git commit f39b50865a13)

Compiled (64-bit) with Qt 5.14.2, with libpcap, with POSIX capabilities (Linux),
with libnl 3, with GLib 2.64.1, with zlib 1.2.11, without SMI, with c-ares
1.16.0, with Lua 5.2.4, with GnuTLS 3.6.13 and PKCS #11 support, with Gcrypt
1.8.5, with MIT Kerberos, with MaxMind DB resolver, with nghttp2 1.40.0, without
brotli, with LZ4, with Zstandard, with Snappy, with libxml2 2.9.10, with
QtMultimedia, without automatic updates, with SpeexDSP (using bundled
resampler), with SBC, with SpanDSP, with bcg729.

Running on Linux 5.4.35-1-MANJARO, with Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
(with SSE4.2), with 15807 MB of physical memory, with locale
LC_CTYPE=en_US.UTF-8, LC_NUMERIC=uk_UA.UTF-8, LC_TIME=uk_UA.UTF-8,
LC_COLLATE=en_US.UTF-8, LC_MONETARY=uk_UA.UTF-8, LC_MESSAGES=en_US.UTF-8,
LC_PAPER=uk_UA.UTF-8, LC_NAME=uk_UA.UTF-8, LC_ADDRESS=uk_UA.UTF-8,
LC_TELEPHONE=uk_UA.UTF-8, LC_MEASUREMENT=uk_UA.UTF-8,
LC_IDENTIFICATION=uk_UA.UTF-8, with light display mode, without HiDPI, with
libpcap version 1.9.1 (with TPACKET_V3), with GnuTLS 3.6.13, with Gcrypt 1.8.5,
with zlib 1.2.11, binary plugins supported (19 loaded).

Built using gcc 9.3.0.
```
[screenshot wireshark main](https://postimg.cc/zL52KZ72)
[screenshot wireshark protocols](https://postimg.cc/K1VBhnkP)
`VERTX_EVENTBUS` appears at Enabled protocols, but there is no such choice in Decode as.

Need your help.

**Comment by noseka1** [comment]
Hello @opavlyuk ,

Thanks for letting me know. The documentation was lacking, it has been improved now. Please, review the udpated [instructions](https://github.com/noseka1/vertx-eventbus-wireshark-dissector/blob/master/vertx_eventbus_dissector.lua#L24-L29) and additional screenshots at the project's [front page](https://github.com/noseka1/vertx-eventbus-wireshark-dissector).

Hope this helps.

**Comment by opavlyuk** [comment]
@noseka1 Thank you! Unfortunately, I'm not very familiar with wireshark, so your updates helped me a lot!

**Comment by opavlyuk** [comment]
@noseka1 btw, could you suggest, how to decode JSON body of eventbus packets, if you know?

**Comment by noseka1** [comment]
@opavlyuk No, I don't know how to configure Wireshark to decode a field as JSON. However, I thought it was a useful feature so I enhanced the script to dissect the JSON bodies of eventbus packets. You can pull the latest version of the script and give it a try.
